version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  fruit-api:
    image: ghcr.io/sachin2605/cast0r:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGOURI: mongodb://root:example@mongo:27017/